#pragma once
#include "UdpProtocol.h"

typedef struct _S_PU_TUNNELING
{
	WCHAR USERID[16];
	WCHAR VIRTUAL_ADDRESS[32];
	USHORT VIRTUAL_PORT;
} S_PU_TUNNELING;

typedef struct _S_PU_TUNNELING_SUCC_U
{
	WCHAR VIRTUAL_ADDRESS[32];
	USHORT VIRTUAL_PORT;
	WCHAR REAL_ADDRESS[32];
	USHORT REAL_PORT;
} S_PU_TUNNELING_SUCC_U;

typedef struct _S_PU_TUNNELING_FAIL_U
{
} S_PU_TUNNELING_FAIL_U;

typedef struct _S_PU_U2C_MOVE_TO
{
	DWORD ROOM_ID;
	DWORD OID;
	FLOAT X;
	FLOAT Y;
	FLOAT Z;
	FLOAT DW;
	FLOAT DX;
	FLOAT DY;
	FLOAT DZ;
	FLOAT SPEED;
	FLOAT BOOSTTIME;
	BOOL ISFIRED;
} S_PU_U2C_MOVE_TO;

typedef struct _S_PU_H2C_MOVE_TO
{
	WCHAR USERID[32];
	DWORD ROOM_ID;
} S_PU_H2C_MOVE_TO;

typedef struct _S_PU_C2U_MOVE_TO
{
	USER_MOVE_TO_DATA USER[8];
} S_PU_C2U_MOVE_TO;

typedef struct _S_PU_U2C_DAMAGE
{
	DWORD USERID;
	DWORD TARGETID;
	FLOAT DAMAGE;
} S_PU_U2C_DAMAGE;

